sudo: false
language: python
matrix:
    include:
    - env: TOXENV=py27
    - python: "3.5"
      env: TOXENV=py35
    - env: TOXENV=py27-pyramid15
    - env: TOXENV=docs
install: pip install tox==1.9.2 coveralls
script: tox
after_success: coveralls
